---
title: Models > Logistic Regression
jupyter: python3
---


<div class="alert alert-info">Estimate a Logistic regression model for binary classification</div>



<!-- pyrsm-teaching-note: roadmap -->
## Teaching Roadmap

Use this notebook to teach binary classification with an interpretable model. Logistic regression models the log-odds of the selected event level, so coefficients are easiest to discuss as odds ratios and predictions are easiest to discuss as probabilities. Students should distinguish statistical evidence about a coefficient from predictive usefulness.
```{python}
import polars as pl
import pyrsm as rsm
```

```{python}
## setup pyrsm for autoreload
%reload_ext autoreload
%autoreload 2
%aimport pyrsm
```

### Example

As an example we will use a dataset that describes the survival status of individual passengers on the Titanic. The principal source for data about Titanic passengers is the Encyclopedia Titanic. One of the original sources is Eaton & Haas (1994) Titanic: Triumph and Tragedy, Patrick Stephens Ltd, which includes a passenger list created by many researchers and edited by Michael A. Findlay. Suppose we want to investigate which factors are most strongly associated with the chance of surviving the sinking of the Titanic. Lets focus on four variables in the database:

- survived = a factor with levels `Yes` and `No`
- pclass = Passenger Class (1st, 2nd, 3rd). This is a proxy for socio-economic status (SES) 1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower
- sex = Sex (female, male)
- age = Age in years

Select `survived` as the response variable and `Yes` in **Choose level**. Select `pclass`, `sex` and `age` as the explanatory variables. In the screenshot below we see that each of the coefficients is statistically significant (p.value < .05) and that the model has some predictive power (Chi-squared statistic < .05). Unfortunately the coefficients from a logistic regression model are difficult to interpret. The `OR` column provides estimated odds-ratios. We see that the odds of survival were significantly lower for 2nd and 3rd class passengers compared to 1st class passenger. The odds of survival for males were also lower than for females. While the effect of age is statically significant, for each extra year in age the odds of survival are not as strongly affected (see also the standardized coefficient).

For each of the explanatory variables the following null and alternate hypotheses can be formulated for the odds ratios:

* H0: The odds-ratio associated with explanatory variable x is equal to 1
* Ha: The odds-ratio associated with explanatory variable x is not equal to 1

The odds-ratios from the logistic regression can be interpreted as follows:

- Compared to 1st class passengers, the odds of survival for 2nd class passengers was 72% lower, keeping all other variables in the model constant.
- Compared to 1st class passengers, the odds of survival for 3rd class passengers was 89.8% lower, keeping all other variables in the model constant.
- Compared to female passengers, the odds of survival for male passengers was 91.7% lower, keeping all other variables in the model constant.
- For an increase in passenger age of 1 year the odds of survival decreased by 3.4%, keeping all other variables in the model constant.

```{python}
titanic = pl.read_parquet("https://github.com/radiant-ai-hub/pyrsm/raw/refs/heads/main/examples/data/data/titanic.parquet")
titanic
```

```{python}
rsm.md("https://raw.githubusercontent.com/radiant-ai-hub/pyrsm/refs/heads/main/examples/data/data/titanic_description.md")
```

```{python}
titanic.head()
```

The two code chunks below test if the categorical order set by the user or data owner is maintained throughout the analysis.

```{python}
levels = titanic["pclass"].dtype.categories.to_list()
levels
```

```{python}
levels.reverse()
titanic = titanic.with_columns(
    pl.col("pclass").cast(pl.Enum(levels))
)
levels = titanic["pclass"].dtype.categories.to_list()
levels
```


<!-- pyrsm-teaching-note: logistic-summary -->
### Logistic regression output

The fitted model estimates survival probabilities through log-odds. In the coefficient table, signs indicate whether a predictor increases or decreases the log-odds of survival relative to the reference level. The odds-ratio plot below translates those effects onto a scale that is usually easier to explain.

```{python}
clf = rsm.model.logistic(
    {"titanic": titanic}, rvar="survived", lev="Yes", evar=["pclass", "sex", "age"]
)
clf.summary()
```


<!-- pyrsm-teaching-note: logistic-predictions -->
### Reading predictions

Prediction output is row-level. For classification models, `prediction` is the estimated probability of the selected event level, not a hard class label. For regression models, it is the fitted numeric outcome. Use predictions for ranking, scoring, and scenario analysis, but evaluate them on data that were not used to choose the model whenever possible.

```{python}
pred = clf.predict(ci=True)
pred
```

```{python}
clf.summary(test="pclass")
```

In addition to the numerical output provided in the _Summary_ tab we can also evaluate the link between `survival`, `class`, `sex`, and `age` visually (see _Plot_ tab). In the screenshot below we see a coefficient (or rather an odds-ratio) plot with confidence intervals. The relative importance of gender and class compared to age clearly stands out. Note: click the check box for standardized coefficients (i.e., `standardize`) in the _Summary_ tab and see if your conclusion changes.


<!-- pyrsm-teaching-note: logistic-odds -->
### Odds ratios

An odds ratio above 1 means the odds of the selected event level are higher than the reference case; below 1 means they are lower. Confidence intervals that include 1 are consistent with no change in odds at the selected confidence level. Odds ratios are not the same as probability differences, especially when baseline probabilities are high or low.

```{python}
clf.plot(plots="or")
```

```{python}
clf.plot("dist")
```

```{python}
clf.plot(plots="corr")
```


<!-- pyrsm-teaching-note: logistic-pdp -->
### Interpreting PDP, ICE, and PIP

Permutation importance (PIP) asks how much model performance changes when one variable is shuffled. Partial dependence plots (PDP) show the average predicted outcome as one variable changes while other variables are held at their observed values. ICE curves show the same relationship one observation at a time, which helps reveal heterogeneity that an average PDP can hide.

```{python}
clf.plot("pdp")
```

```{python}
clf.plot("pdp")
```

```{python}
clf.plot("pdp", ice=True)
```

```{python}
clf.plot("pip")
```

```{python}
pip_values = clf.plot(plots="pip", ret=True)
pip_values
```

© Vincent Nijs (2026)
